v1.6.0 Fix most features.
Pythe1337N/garmin-connect pull request #56
Opened 2023-10-02 03:27 UTC by gooin

-   [x] New HttpClient class
-   [x] Login and get user token
-   [x] Garmin URLs works with `garmin.cn` and `garmin.com`
-   [x] Auto refresh Ouath2 token
-   [x] Oauth1,Oauth2 token import and export.
-   [x] Download Activity, countActivities, getActivities, getActivity, getUserProfile, getUserSettings
-   [x] Upload Activity, delete Activity
-   [ ] Implementation of other methods, such as Badge,Workout,Gear etc
-   [ ] Handle MFA
-   [x] Handle Account locked
-   [ ] Unit test
-   [ ] Listeners

2023-10-02 08:20 UTC, Abasz commented
Is there a specific reason that you are still using the `/proxy/` path on the connect api? 

Actually, for some reasons I got errors on that and moved to `connectapi.garmin.com` without the `/proxy/`. I checked and I think this is used by Garth as well.

So for instance, activity list service: `https://connectapi.garmin.com/activitylist-service/activities/search/activities`
or download service: `https://connectapi.garmin.com/download-service/files/activity/`

2023-10-02 08:38 UTC, gooin commented
> > > Is there a specific reason that you are still using the `/proxy/` path on the connect api?
> > > Actually, for some reasons I got errors on that and moved to `connectapi.garmin.com` without the `/proxy/`. I checked and I think this is used by Garth as well.
> > > So for instance, activity list service: `https://connectapi.garmin.com/activitylist-service/activities/search/activities` or download service: `https://connectapi.garmin.com/download-service/files/activity/`
> > 
> > 
> > I use `UrlClass.ts` not `url.ts`
> 
> you are right... sorry I missed that.

I Will delete it later.😂

2023-10-02 15:06 UTC, gooin commented
> > > Is there a specific reason that you are still using the `/proxy/` path on the connect api?
> > > Actually, for some reasons I got errors on that and moved to `connectapi.garmin.com` without the `/proxy/`. I checked and I think this is used by Garth as well.
> > > So for instance, activity list service: `https://connectapi.garmin.com/activitylist-service/activities/search/activities` or download service: `https://connectapi.garmin.com/download-service/files/activity/`
> > 
> > 
> > I use `UrlClass.ts` not `url.ts`
> 
> you are right... sorry I missed that.

@Abasz removed...

2023-10-03 13:07 UTC, kspetrov commented
@gooin Hi! What about workout methods? Or this is not in your plan?

2023-10-03 13:08 UTC, gooin commented
Yes, I'm working on this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Kirill Petrov ***@***.***>
Sent: Tuesday, October 3, 2023 9:07:24 PM
To: Pythe1337N/garmin-connect ***@***.***>
Cc: Yan Zhitao ***@***.***>; Mention ***@***.***>
Subject: Re: [Pythe1337N/garmin-connect] v1.6.0 Fix most features. (PR #56)


@gooin<https://github.com/gooin> Hi! What about workout methods? Or this is not in your plan?

—
Reply to this email directly, view it on GitHub<https://github.com/Pythe1337N/garmin-connect/pull/56#issuecomment-1744943799>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADJDEBL3WJ3S5L3STP7ABV3X5QEYZAVCNFSM6AAAAAA5O2JRO2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBUHE2DGNZZHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-03 13:12 UTC, kspetrov commented
Perfect! :) Thanks a lot!!!

2023-10-03 15:27 UTC, gooin commented
> Perfect! :) Thanks a lot!!!

Latest commit added workout methods. See https://github.com/Pythe1337N/garmin-connect/pull/56/commits/901a70f2b217e85454d596baf9d640023a34aa34

2023-10-09 19:49 UTC, pauly commented
Is the whole interface changing here? The original examples aren't working, neither is my code if I switch to this branch.
I see the change from 

```
await GCClient.login(process.env.GUSER, process.env.GPASS)
const userProfile = await GCClient.getUserProfile()
const stepData = await GCClient.getSteps(new Date(date))
```
now there is no getSteps()

2023-10-10 02:06 UTC, gooin commented
> Is the whole interface changing here? The original examples aren't working, neither is my code if I switch to this branch. I see the change from
> 
> ```
> await GCClient.login(process.env.GUSER, process.env.GPASS)
> const userProfile = await GCClient.getUserProfile()
> const stepData = await GCClient.getSteps(new Date(date))
> ```
> 
> now there is no getSteps()

steps, sleep, weight, gear are not implemented yet, see `GarminConnect.ts`

2023-10-19 08:33 UTC, Pythe1337N requested changes

2023-10-19 08:33 UTC, Pythe1337N commented on package.json
> +    "version": "1.6.5",
Please do not bump version numbers, this will be done along with a new release

2023-10-19 08:36 UTC, merged

2023-10-26 13:34 UTC, app4g commented
Based on the above (first post) the gear link/unlink is still WIP correct?

https://github.com/Pythe1337N/garmin-connect/pull/46

I'm trying to give it a go but am getting Status  403 Forbidden

```PUT https://connectapi.garmin.com/gear-service/gear/link/(gearUUID)/activity/(activityId)```

```
{
  "message": null,
  "error": "ForbiddenException"
}
```

this used to work using the previous Web authentication style.

2023-10-26 15:51 UTC, matin commented
@gooin well done! 👏🏽