Re-add "getSteps" API
Pythe1337N/garmin-connect pull request #58
Opened 2023-10-20 12:41 UTC by loic294

2023-10-20 13:50 UTC, Pythe1337N requested changes

2023-10-20 13:50 UTC, Pythe1337N commented on package.json
> +    "version": "1.6.1",
Do not bump version

2023-11-03 12:26 UTC, neogermi commented
Hey, what is holding this PR back? It would be great to have the getSteps back soon :-) 

Thank you for your work and let me know if I can help somehow.

2023-11-03 12:44 UTC, Pythe1337N commented
I requested changes since the versioning and tagging will be a bit messed up if version number in package.json. I guess i can make a temporary branch and fix it

2023-11-03 12:45 UTC, merged